version: '3'

services:
    blog_mysql:
      image: mysql:8
      container_name: blog_mysql_cn
      ports:
        - 33062:3306
      volumes:
        - ./docker/mysql/data:/var/lib/mysql
        - ./docker/mysql/conf:/etc/mysql/conf.d
      environment:
        - MYSQL_ROOT_PASSWORD=root
      command:
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_general_ci
        --explicit_defaults_for_timestamp=true
        --lower_case_table_names=0
        --host_cache_size=0
    blog_nginx:
      image: nginx
      container_name: blog_gin_nginx
      ports:
        - '8011:80'
        - '443:443'
      volumes:
        - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
        - ./docker/nginx/config/conf.d:/etc/nginx/conf.d
    blog_api:
      image: gin_api:v1
      container_name: blog_api_cn
      ports:
        - '6008:6008'
      depends_on:
        - blog_mysql
        - blog_nginx



