version: '3'
services:
  blog_mysql:
    image: mysql:8.0
    container_name: blog_mysql_cn
    restart: on-failure
    ports:
      - "6001:3306"
    volumes:
      - ./docker/mysql_dev/data:/var/lib/mysql
      - ./docker/mysql_dev/my.cnf:/etc/my.cnf
      - ./docker/mysql_dev/init:/docker-entrypoint-initdb.d
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - MYSQL_DATABASE=gin_vue_blog
      - MYSQL_USER=db_blog_user
      - MYSQL_PASSWORD=db_blog_pass
      - MYSQL_ROOT_PASSWORD=root
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    networks:
      - blog_gin_net
  blog_mysql_admin:
    image: phpmyadmin/phpmyadmin
    container_name: blog_mysql_admin_cn
    ports:
      - "6002:80"
    environment:
      - PMA_ARBITRARY=0
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=blog_mysql
    depends_on:
      - blog_mysql
    networks:
      - blog_gin_net

  blog_nginx:
    image: nginx
    container_name: blog_nginx_cn
    restart: on-failure
    ports:
      - "6003:6003"
      - "6004:6004"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ../admin/dist:/app/admin
      - ../vue-front/dist:/app/front
    links:
      - blog_api
    networks:
      - blog_gin_net

  blog_api:
    image: blog_gin_api:v1
    container_name: blog_api_cn
    restart: on-failure
    ports:
      - "6008:6008"
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /usr/share/zoneinfo/Asia/:/usr/share/zoneinfo/Asia/
    links:
      - blog_mysql
    depends_on:
     - blog_mysql
    networks:
      - blog_gin_net

networks:
  blog_gin_net:
    driver: bridge

