version: '3'

services:
    blog_mysql:
      image: mysql:8
      container_name: blog_mysql_cn
      ports:
        - 33062:3306
      restart: always
      volumes:
        - ./docker/mysql/data:/var/lib/mysql
        - ./docker/mysql/conf.d:/etc/mysql/conf.d
      command:
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_general_ci
        --explicit_defaults_for_timestamp=true
        --default-authentication-plugin=mysql_native_password
      environment:
        - TZ=Asia/Shanghai
        - LANG=C.UTF-8
        - MYSQL_ROOT_PASSWORD=root
      networks:
        default:
          ipv4_address: 172.25.0.1
    blog_api_server:
      image: blog_gin_api
      container_name: blog_api_server_cn
      restart: on-failure
      ports:
        - '6008:6008'
      depends_on:
        - blog_mysql
      networks:
        default:
          ipv4_address: 0.0.0.0/6008
networks:
  default:
    external:
      name: blog_api

