version: '3'
services:
  mysql:
    image: mysql:8
    container_name: mysql8
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --default-authentication-plugin=mysql_native_password
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=root
